services:
  app:
    image: backend
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"

    environment:
      - PORT=4000
      - PORT_FRONTEND=8081
      - IP=192.168.1.4 # IP de su pc
    restart: "no"
  mongo:
    image: mongo
    restart: always
    environment:
      - name=value
    ports:
      - 27017:27017
    container_name: mondodb
    volumes:
      - ${pwd}/db/mongodb:/data/db
  